apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
  labels:
    app: sa-web-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: sa-web-app
      labels:
        app: sa-web-app
    spec:
      containers:
      - name: sa-web-app
        image: udit7294/sentiment-analysis-web-app
        imagePullPolicy: Always
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic-lb"
        ports:
          - containerPort: 8080
  selector:
    matchLabels:
      app: sa-web-app
